server:
  port: 8090 # 服务端口

spring:
  application:
    name: payment-weixin # 服务名字
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_weixin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456

mybatis-plus:
  configuration: #sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:cn/itzhouq/payment/weixin/mapper/xml/*.xml

logging:
  level:
    root: debug


